language: node_js
sudo: false
node_js:
- '5.3'
branches:
  except:
  - /^v[0-9\.]+/
before_install:
 - npm install -g coveralls
 - npm install -g pr-bumper
 - echo "To be replaced by pr-bumper check "
before_script:
 - echo "Executing the before script"
after_success:
 - cat coverage/lcov.info | coveralls
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: OYfwytcULr/q5jXodtEMvTY+4YhbvPxF2KrYlfUYO/bxQ1qog9fyc19BFTeCyYA0XT2tq7ctP6lh5TLf48r/AgfbRUl3vdtPA6f5bur9XxxWYJkROxzbgAmzwAb+PCUdM/D7whsCvFaEBnKVO5v+5W0J4HgXqT6Ad9+AQJsHgSldaScvPeLBLBYIRMZbhSmJZAxGgLZJFpYpXyJQl1WXZRLeHRciTgG4ugb1s91WW8N0Mhn5HKYhfCj2vQv8folTdY8/q7Uo/cjC71XBfOrR0bH02xcS6JZ5t54HpQgeq4RMO3rNaWODhOaEIuauUxh/BnMq+Lngz8I0cma6zmVuRxk5b01tRVzJJkKPoAFKXwe/KghzCi1snfKhhuF54JagKsMtCLg5UOuhaEdoD0L6VUTVjGo7sXrDDhW1SR02I7EXsWsmGqqYUSkR22uuUmdq0BMYcOz56T4fn+/IFvRO71yD2vJ0EIAMRQKCaWrTTDhwKG4DOIwCjZA0gL1GK8NLCVGREEQEMJw8fsXcypNuXRVLL1PZS+E7/aivSbbU6ji0VqqQhk3JZyBsuuIsF1bRxnwUwqhahURq8C7B8YflxW/bMzXzxmljkAmJyCjhKRyEVsrQs3dk5gC0vydhz0fzZL+vPB0zQi3deHE3UN0JAkjfNMRlxy8I6pMwc9nCg/g=
before_deploy:
 - echo "To be replaced by pr-bumper bump "
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: MMMrKAVIbU7ZzCTeOfgRGSUPJx0s0DBDS/zLwYcOdwMDsJZuZqLKVcm7rXj6srTHIGMpwzP5FTID9S2sHuVHtnqOfOByeJB0AvlBkHNQMgqKQvSCQxzMwbVz7FCFMaFQDkL2o3aKeQV2I5mxXfT+/xXYHTZfdDuzkFD4mI9ygaP+EPJnDIwf5ckxhhcXj0Rckpz8X/ZgS/owQLcTicKzly96378im77Nl6KBe585E+9Om79F7GHlewa+D0Hz2gLoX61RnXvsKG4HUrEZDF5TY0RIwxkvYMEQuPA6rDDjN2qnMuZAdNqVT74sSG8cGF8D/J4RVUQ9IssSltrRgBwPa+lnmfmL9+sxCwW5GY+VoKUbIh3kJkcfN1xxFCOAnTPxqj9Mmi1Zad/NRe1dniClKoMxm0IYUM7ZevXooLhOhCfkGOfXgibv+MHoQ4IyicIjS2K7xcJLLX5HSumnv8wD0iQuRCF9mpp1iyLHmVf/g0vo7HURt+PN8sSh1F8nirJ2zUCtp5NWBc21MhOQEUmPng/lC350NInMoKpO7SZHBKn+qzpKRARCoYJfiyQ4G9i/F29B9pa+fAKYnYEO1d+OfBIbR1FbTzbgwt1sHUYoDNYRaGKUzt0Q+atveZbA37mN197P0eu5/2ENA1gSVwE6+w71FQPb+pGw3Gu4bRVPJnc=
  on:
    branch: master
    tags: false
notifications:
  slack:
    secure: mUroABVyHA24GnPKx1jMSpcG92R0EAjrv0JPSqLHtc5NVkg+8gs4Vf0FY+hyKj7t9SQ08V/MLtmBXCZbe/VeMvYFbv/AW+gIzuBX2YboP6t/FzFU9JnV3Qz33gsP/UEK0Rnl00Zjibt4A0d3uwsvCy4tjccibnYuXOW2KfVkGmn7I9oUTlN1HSTs6h70HfP/IZvmpzXwKNmmBDPVUhyx0FO/4hms0SColLv71C8xwEoF4E2gOoKSJRLph58H5rOWxqi/HPZBzTwFpxCRGtTTR1XgeXUdQs5+2XVTXIpz5Kin4YTgKzEb9TmsdwpNeQx3vi3RVHnEOJhSfZ5IFDb7NSE/tUhtnrd5vQbbcN+0EwLHbcWL0gi5/IOAvhT5APZB3yPM1p+hEx7KKrdLyPsRNqfAtDgFDZ84ECvrBeRMwXzF7HhKgJasxmEuMXn0dKSHMShwlV1Vo057hoImEkv3DZN5yBUqOgSTBxtk2STgyUPwWEuhQM5flHc3EEe/KK4K98RgWsqlgU1+S5ZvsgLNQrOUNr9cV706ubKu2e+nY/PQadFuModrsjN+ZTOImZFke18XBXxASY5+EFyfHk8SWR+r6cDCaBVodTnHrT0p1/jqXEboobJm1wqWBRNM75P4PhHcCCisQ0cc9jCE6VJcdhmtLzwSM/NvIvwQXMvQVCA=
